server {
  listen 8080;
  server_name _;
  absolute_redirect off;
  root /usr/share/nginx/html;
  index index.html;

  location = / {
    return 302 /fg/;
  }

  location = /fg {
    return 301 /fg/;
  }

  location /fg/ {
    try_files $uri $uri/ /fg/index.html;
  }
}
